### ISSUE TITLE
Need Loader after click on WebD wing button

### ISSUE THREAD

**Issue by CodHeK** [pradeepgangwar/GeekHaven-WebD#2]

**Comment by agbilotia1998** [comment]
Any CSS template would do that.

**Comment by CodHeK** [comment]
Yep any good looking loader !

**Comment by pradeepgangwar** [comment]
PR from @agbilotia1998 merged. Thanks for contribution. 😃

**Comment by pradeepgangwar** [comment]
Add a more interesting loader than existing one. Refer #16 to see changes made to add existing preloader.
